### ISSUE TITLE
panic after running clangd

### ISSUE THREAD

**Issue by cnt0** [kak-lsp/kak-lsp#425]
I got the following debug output after running `kak -s foobar file.cpp`:
```bash
$ kak-lsp -s foobar
Dec 15 08:40:18.576 INFO Starting main event loop, module: kak_lsp::session:29
Dec 15 08:40:23.745 INFO Starting Language server `clangd `, module: kak_lsp::language_server_transport:21
thread 'Controller' panicked at 'Failed to parse response: Error("data did not match any variant of untagged enum TextDocumentSyncCapability", line: 0, column: 0)', src/context.rs:97:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 15 08:40:23.825 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:18
Dec 15 08:40:23.831 ERRO Language server error: I[08:40:23.824] clangd version 11.0.0
I[08:40:23.824] PID: 195592
I[08:40:23.824] Working directory: <edited out>
I[08:40:23.824] argv[0]: clangd
I[08:40:23.824] Starting LSP over stdin/stdout
I[08:40:23.824] <-- initialize(0)
I[08:40:23.825] --> reply:initialize(0) 0 ms
E[08:40:23.825] Transport error: Input/output error
I[08:40:23.826] LSP finished, exiting with status 1
, module: kak_lsp::language_server_transport:52
Dec 15 08:40:24.826 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:20
Dec 15 08:40:24.826 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:18
Dec 15 08:40:24.826 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:20
Dec 15 08:40:24.826 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:18
Dec 15 08:40:24.826 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:20
thread 'main' panicked at 'Dec 15 08:40:29.704Box<Any>', src/thread_worker.rs:29 :17
INFO Waiting for Controller to finish..., module: kak_lsp::thread_worker:18
Dec 15 08:40:29.704 INFO ... Controller terminated with err, module: kak_lsp::thread_worker:20
Dec 15 08:40:29.705 INFO Waiting for Messages to editor to finish..., module: kak_lsp::thread_worker:18
Dec 15 08:40:29.705 INFO ... Messages to editor terminated with ok, module: kak_lsp::thread_worker:20
```
versions:
```bash
$ kak -version
Kakoune v2020.09.01
$ kak-lsp --version  
kak-lsp 8.0.0
$ clangd --version
clangd version 11.0.0
```

**Comment by krobelus** [comment]
Thanks for the report, I can reproduce. You can [upgrade](https://github.com/kak-lsp/kak-lsp#from-the-source) to the development version which works here.

**Comment by cnt0** [comment]
yes it works with development version. I guess I should wait for it to appear in archlinux repos

**Comment by krobelus** [comment]
The release is not out yet; you can also install `kak-lsp-git` from AUR: https://aur.archlinux.org/packages/kak-lsp-git/
