### ISSUE TITLE
Error in debug logs with elm-language-server

### ISSUE THREAD

**Issue by jaredramirez** [kak-lsp/kak-lsp#484]
Hey there,

I'm having a problem getting kak-lsp to work the [elm-langauge-sever](https://github.com/elm-tooling/elm-language-server). I have the latest kak-lsp installed from `master` through plug.kak. I have the debug log setup and whenever I open an elm file, I see this error in the logs:
```
// lots of things every very similar to the line immediate next
May 06 14:33:24.254 DEBG To editor `72605`: echo -debug LSP: 'Adding /Users/jaredramirez/dev/github/replenysh/core/join/src/elm/Session.elm', module: kak_lsp::editor_transport:84
May 06 14:33:24.254 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Done parsing all files for /Users/jaredramirez/dev/github/replenysh/core/join/elm.json"}}, module: kak_lsp::language_server_transport:151
May 06 14:33:24.255 DEBG From server: {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"codeActionProvider":{"resolveProvider":true},"codeLensProvider":{"resolveProvider":true},"completionProvider":{"triggerCharacters":["."]},"definitionProvider":true,"documentFormattingProvider":true,"documentSymbolProvider":{"label":"Elm"},"executeCommandProvider":{"commands":["elmLS.elmMakeFixer-a3cac0ed8ba6f30f5c7810e0a01b6a44","elm.installPackage"]},"foldingRangeProvider":true,"hoverProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"textDocumentSync":2,"workspaceSymbolProvider":true,"workspace":{"fileOperations":{"didCreate":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.elm","matches":"file"}}]},"willRename":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.elm","matches":"file"}},{"scheme":"file","pattern":{"glob":"**/","matches":"folder"}}]},"willDelete":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.elm","matches":"file"}}]}}},"linkedEditingRangeProvider":true}}}, module: kak_lsp::language_server_transport:151
May 06 14:33:24.255 ERRO panic: panicked at 'Failed to parse response: Error("data did not match any variant of untagged enum LinkedEditingRangeServerCapabilities", line: 0, column: 0)', src/context.rs:127:64, module: kak_lsp:265
May 06 14:33:24.255 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:19
May 06 14:33:24.255 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:188
May 06 14:33:24.255 DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:87
May 06 14:33:24.266 DEBG To editor `72605`: echo -debug LSP: 'Adding /Users/jaredramirez/dev/github/replenysh/core/join/src/elm/Api/InputObject.elm', module: kak_lsp::editor_transport:84
May 06 14:33:24.270 DEBG Language server closed pipe, stopping reading, module: kak_lsp::language_server_transport:129
May 06 14:33:24.277 DEBG To editor `72605`: echo -debug LSP: 'Adding /Users/jaredramirez/dev/github/replenysh/core/join/src/elm/Api/Interface.elm', module: kak_lsp::editor_transport:84
// lots of things every very similar to the line immediate before
```

From this, the lines that jump out is:
```
May 06 14:33:24.255 DEBG From server: {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"codeActionProvider":{"resolveProvider":true},"codeLensProvider":{"resolveProvider":true},"completionProvider":{"triggerCharacters":["."]},"definitionProvider":true,"documentFormattingProvider":true,"documentSymbolProvider":{"label":"Elm"},"executeCommandProvider":{"commands":["elmLS.elmMakeFixer-a3cac0ed8ba6f30f5c7810e0a01b6a44","elm.installPackage"]},"foldingRangeProvider":true,"hoverProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"textDocumentSync":2,"workspaceSymbolProvider":true,"workspace":{"fileOperations":{"didCreate":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.elm","matches":"file"}}]},"willRename":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.elm","matches":"file"}},{"scheme":"file","pattern":{"glob":"**/","matches":"folder"}}]},"willDelete":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.elm","matches":"file"}}]}}},"linkedEditingRangeProvider":true}}}, module: kak_lsp::language_server_transport:151
May 06 14:33:24.255 ERRO panic: panicked at 'Failed to parse response: Error("data did not match any variant of untagged enum LinkedEditingRangeServerCapabilities", line: 0, column: 0)', src/context.rs:127:64, module: kak_lsp:265
```

I can post the full log file if that would be helpful too.

Additionally, here's my `kak-lsp.toml` (copied from elm-language-server's README):
```toml
[language.elm]
filetypes = ["elm"]
roots = ["elm.json"]
command = "elm-language-server"
```

I'm not sure if this is a kak-lsp problem or an elm-language-server problem or a problem with how they interact. Any help is appreciated!

**Comment by krobelus** [comment]
Hi, can you try again with latest master. I think it is fixed but I haven't been able to run `elm-language-server` successfully. I get

`ERRO Error response from server: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "Request initialize failed with message: Attempted to resolve unregistered dependency token: \"ElmWorkspaces\"", data: None }, id: Num(0) }, module: kak_lsp::controller:160`

(BTW it looks like the `--stdio` arg in our default `kak-lsp.toml` is obsolete?)

**Comment by jaredramirez** [comment]
Fixed with latest master, thank you so much @krobelus!!
