### ISSUE TITLE
no flags using Eclipse LSP

### ISSUE THREAD

**Issue by basbebe** [kak-lsp/kak-lsp#559]

**Comment by basbebe** [comment]
also opened an issue in Eclipse JDT Language Server: https://github.com/eclipse/eclipse.jdt.ls/issues/1938

**Comment by dzamo** [comment]
I do get flags in the gutter for Java e.g.

![image](https://user-images.githubusercontent.com/9107319/141293873-f1c3f50d-7779-41a9-b43c-8317bb4ad93f.png)

**Comment by krobelus** [comment]
> It does work for projects, e.g. eclips.jdt.ls/
It does not, however, work when opening single files…

that kind of makes sense because you specify the path to the project in your arguments. Let's maybe ask the language server folks to maybe emit warnings in that case.

Last time I tried the Java language server was a bit painful to set up. Do they still not ship a wrapper script? The Archlinux package adds one for example.

I guess the Eclipse language server always requires a valid eclipse workspace.. so it can't just pick up the `pom.xml` in the current directory etc..

**Comment by dzamo** [comment]
> Last time I tried the Java language server was a bit painful to set up. Do they still not ship a wrapper script? The Archlinux package adds one for example.

@krobelus https://github.com/eclipse/eclipse.jdt.ls/issues/748

Btw, any thoughts about `kak-lsp: java language server doesn't support method workspace/executeCommand` which both @basbebe and I get...

**Comment by krobelus** [comment]
> Btw, any thoughts about kak-lsp: java language server doesn't support method workspace/executeCommand

that's how we apply code actions like `Organize Imports`. I'd need to check if there's another method, that they support.
It should be easy by just reading the language server trace of another editor like VSCode (assuming that one works?)

What would help would be a runnable Java example project, then I don't have to figure out how to set that up.
Check the test scripts in the `test/` folder, each of those sets up a file an successfully runs something (we even have some code action tests).

**Comment by dzamo** [comment]
@krobelus Looks like whacked my installation of VSCodium at some point so I'll need to get it again.  For now, this tiny Java project is an example of one that works with my kak-lsp and eclipse.jdt.ls

https://github.com/jenkins-docs/simple-java-maven-app

**Comment by krobelus** [comment]
I didn't manage to get the language server working yet.
I'm using java 17 and [this package of the eclipse language server](https://aur.archlinux.org/packages/jdtls/). (Yet I don't have eclipse installed.)

I'm using the default config except for the paths which I changed like this:

```
    # "/path/to/eclipse.jdt.ls/repository/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar",
    "/usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar",
    "-configuration",
    "/usr/share/java/jdtls/config_linux/",
    # "/path/to/eclipse.jdt.ls/repository/config_linux",
    "-data",
    "/home/johannes/.eclipse-workspace/",
    # "/path/to/eclipse-workspace",
```

where my eclipse workspace is an empty directory.

Debug log below. Is there anything obvious I'm doing wrong?

<details>

```
Nov 11 22:06:15.889 INFO Starting main event loop, module: kak_lsp::session:28
Nov 11 22:06:15.891 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_JAVA, module: kak_lsp::project_root:58
Nov 11 22:06:15.892 INFO Found project root "/home/johannes/git/simple-java-maven-app" because it contains ".git", module: kak_lsp::project_root:41
Nov 11 22:06:15.892 DEBG Routing editor request to Route { session: "520504", language: "java", root: "/home/johannes/git/simple-java-maven-app" }, module: kak_lsp::session:94
Nov 11 22:06:15.892 DEBG Spawning a new controller for Route { session: "520504", language: "java", root: "/home/johannes/git/simple-java-maven-app" }, module: kak_lsp::session:116
Nov 11 22:06:15.893 INFO Starting Language server `java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.level=ALL -Dfile.encoding=utf-8 --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -noverify -Xmx1G -jar /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration /usr/share/java/jdtls/config_linux/ -data /home/johannes/.eclipse-workspace/`, module: kak_lsp::language_server_transport:20
Nov 11 22:06:15.896 DEBG To server: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"markdown":{"parser":"kak-lsp","version":"11.0.1-snapshot"}},"offsetEncoding":["utf-16"],"textDocument":{"callHierarchy":{"dynamicRegistration":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":false,"isPreferredSupport":false},"codeLens":{"dynamicRegistration":false},"colorProvider":{"dynamicRegistration":false},"completion":{"completionItem":{"commitCharactersSupport":false,"deprecatedSupport":false,"documentationFormat":["markdown","plaintext"],"preselectSupport":false,"snippetSupport":false},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":false,"dynamicRegistration":false},"declaration":{"dynamicRegistration":false,"linkSupport":false},"definition":{"dynamicRegistration":false,"linkSupport":false},"documentHighlight":{"dynamicRegistration":false},"documentLink":{"dynamicRegistration":false,"tooltipSupport":false},"documentSymbol":{"dynamicRegistration":false},"formatting":{"dynamicRegistration":false},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":false},"implementation":{"dynamicRegistration":false,"linkSupport":false},"onTypeFormatting":{"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":false},"rangeFormatting":{"dynamicRegistration":false},"references":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false,"prepareSupport":false},"semanticTokens":{"dynamicRegistration":false,"formats":["relative"],"requests":{"full":true,"range":false},"tokenModifiers":["readonly","documentation","constant"],"tokenTypes":["namespace","string","comment","operator","function","keyword","type","variable"]},"signatureHelp":{"contextSupport":false,"dynamicRegistration":false,"signatureInformation":{"documentationFormat":["plaintext"],"parameterInformation":{"labelOffsetSupport":false}}},"synchronization":{"didSave":true,"dynamicRegistration":false,"willSave":false,"willSaveWaitUntil":false},"typeDefinition":{"dynamicRegistration":false,"linkSupport":false}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":false,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"executeCommand":{"dynamicRegistration":false},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"changeAnnotationSupport":{},"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","delete","rename"]},"workspaceFolders":false}},"clientInfo":{"name":"kak-lsp","version":"11.0.1-snapshot"},"processId":520619,"rootPath":"/home/johannes/git/simple-java-maven-app","rootUri":"file:///home/johannes/git/simple-java-maven-app","trace":"off"},"id":0}, module: kak_lsp::language_server_transport:177
Nov 11 22:06:15.905 DEBG From editor: 
session  = "520504"
buffile  = "/home/johannes/git/simple-java-maven-app/src/main/java/com/mycompany/app/App.java"
filetype = "java"
version  = 1
method   = "textDocument/didChange"
[params]
draft    = """
package com.mycompany.app;

/**
 * Hello world!
 */
public class App
{

    private final String message = \"Hello World!\";

    public App() {}

    public static void main(String[] args) {
        System.out.println(new App().getMessage());
    }

    private final String getMessage() {
        return message;
    }

}
"""
, module: kak_lsp::editor_transport:129
Nov 11 22:06:15.906 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_JAVA, module: kak_lsp::project_root:58
Nov 11 22:06:15.907 INFO Found project root "/home/johannes/git/simple-java-maven-app" because it contains ".git", module: kak_lsp::project_root:41
Nov 11 22:06:15.907 DEBG Routing editor request to Route { session: "520504", language: "java", root: "/home/johannes/git/simple-java-maven-app" }, module: kak_lsp::session:94
Nov 11 22:06:15.907 DEBG Language server is not initialized, parking request, module: kak_lsp::controller:99
Nov 11 22:06:16.177 ERRO Failed to parse header, module: kak_lsp::language_server_transport:74
Nov 11 22:06:16.177 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:19
Nov 11 22:06:16.177 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:188
Nov 11 22:06:16.177 DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:87
Nov 11 22:06:16.193 ERRO Language server error: OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
An exception occurred while writing to the platform log:
java.io.FileNotFoundException: /usr/share/java/jdtls/config_linux/1636664776125.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:155)
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2506)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2388)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2325)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Logging to the console instead.
!ENTRY org.eclipse.equinox.launcher 4 0 2021-11-11 22:06:16.126
!MESSAGE Exception looking for eclipse_11600.so in JAR file: /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20210928-1041.jar
An exception occurred while writing to the platform log:
java.io.FileNotFoundException: /usr/share/java/jdtls/config_linux/1636664776125.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:155)
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2506)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2388)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2326)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Logging to the console instead.
!STACK
java.nio.file.AccessDeniedException: /usr/share/java/jdtls/config_linux/org.eclipse.equinox.launcher
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2313)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

An exception occurred while writing to the platform log:
java.io.FileNotFoundException: /usr/share/java/jdtls/config_linux/1636664776125.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:155)
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2506)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2388)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2325)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Logging to the console instead.
!ENTRY org.eclipse.equinox.launcher 4 0 2021-11-11 22:06:16.166
!MESSAGE Exception looking for eclipse_11600.so in JAR file: /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20210928-1041.jar
An exception occurred while writing to the platform log:
java.io.FileNotFoundException: /usr/share/java/jdtls/config_linux/1636664776125.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:155)
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2506)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2388)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2326)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Logging to the console instead.
!STACK
java.nio.file.AccessDeniedException: /usr/share/java/jdtls/config_linux/org.eclipse.equinox.launcher
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2313)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

An exception occurred while writing to the platform log:
java.io.FileNotFoundException: /usr/share/java/jdtls/config_linux/1636664776125.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:155)
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2506)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2388)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2325)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Logging to the console instead.
!ENTRY org.eclipse.equinox.launcher 4 0 2021-11-11 22:06:16.168
!MESSAGE Exception looking for eclipse_11600.so in JAR file: /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20210928-1041.jar
An exception occurred while writing to the platform log:
java.io.FileNotFoundException: /usr/share/java/jdtls/config_linux/1636664776125.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:155)
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2506)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2388)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2326)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Logging to the console instead.
!STACK
java.nio.file.AccessDeniedException: /usr/share/java/jdtls/config_linux/org.eclipse.equinox.launcher
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2313)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:485)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

An exception occurred while writing to the platform log:
java.io.FileNotFoundException: /usr/share/java/jdtls/config_linux/1636664776125.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:155)
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2506)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2388)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2325)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:495)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Logging to the console instead.
!ENTRY org.eclipse.equinox.launcher 4 0 2021-11-11 22:06:16.170
!MESSAGE Exception looking for eclipse_11600.so in JAR file: /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.400.v20210928-1041.jar
An exception occurred while writing to the platform log:
java.io.FileNotFoundException: /usr/share/java/jdtls/config_linux/1636664776125.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:155)
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2506)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2388)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2326)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:495)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Logging to the console instead.
!STACK
java.nio.file.AccessDeniedException: /usr/share/java/jdtls/config_linux/org.eclipse.equinox.launcher
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2313)
	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:535)
	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:495)
	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:579)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

, module: kak_lsp::language_server_transport:58
Nov 11 22:06:17.178 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:21
Nov 11 22:06:17.178 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:19
Nov 11 22:06:17.178 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:21
Nov 11 22:06:17.179 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:19
Nov 11 22:06:17.179 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:21
```

</details>

**Comment by dzamo** [comment]
@krobelus it looks to me like jdt.ls wants to extract something from a jar file under `/usr/share/java/jdtls/config_linux/` but it the user it's running under does not have the needed access...

**Comment by krobelus** [comment]
got it, looks like the package can't work like this (as non-root).
I'll try the official installation instructions later.

**Comment by dzamo** [comment]
I run it as non-root.  If I just launch the lang server (using a wrapper script) I see this.

```sh
➜  ~ jdt-ls.sh
Content-Length: 123

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"12 Nov 2021, 08:58:12 Main thread is waiting"}}
```
I looked at my installation, which I put at `/opt/eclipse.jdt.ls/` and I see I just made my personal user own every file under there, which was probably a bit hacky.

**Comment by krobelus** [comment]
> I looked at my installation, which I put at `/opt/eclipse.jdt.ls/` and I see I just made my personal user own every file under there, 

Yes. I'd expect this program to never try to write to its own installation directory.
It should rather write to `~/.cache` for data that is always safe to delete, or `~/.local/share` for persistent storage of user data, for example, a list of projects that it has analyzed.

**Comment by dzamo** [comment]
Completely agree!  It may only be on the first launch after a new installation, a sort of "complete the installation by unpacking native libs from jars" kind of step.  But I'm doing a lot of guessing now.  Shout if I can help with anything when you get back to this!

**Comment by dzamo** [comment]
I'll just add this on.  I experimented with removing my user's write permission to the jdt.ls install dir and, while I think this is a later and milder error than you're getting, under default settings the stuff does want to write to at least some places under the install dir:

```
<title>Invalid Configuration Location</title>The configuration area at '/opt/eclipse.jdt.ls/repository/config_linux' is not writable.  Please choose a writable location using the '-configuration' command line option.
```

**Comment by krobelus** [comment]
I just downloaded a release and unpacked it to a user dir

I do get the error flags on the jenkins demo project:

![image](https://user-images.githubusercontent.com/6853872/141515825-c362dc66-8905-463d-9213-c91796b880d0.png)

I can reproduce the problem with `Organize Imports`. I'll take a look.

One issue is that the sever sends diagnostics for a directory (see below), instead of a file.
I think diagnostics should only be sent for files. At least the specification [implies that an URI should refer to a "document"](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#documentUri)

Anyway, I added a workaround for that, this shouldn't be a problem.

<details>

```json
Nov 12 19:05:28.077 DEBG From server: {
  "jsonrpc": "2.0",
  "method": "textDocument/publishDiagnostics",
  "params": {
    "uri": "file:///home/johannes/git/simple-java-maven-app",
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 0
          }
        },
        "severity": 2,
        "code": "0",
        "source": "Java",
        "message": "The compiler compliance specified is 1.6 but a JRE 17 is used"
      },
      {
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 0
          }
        },
        "severity": 2,
        "code": "0",
        "source": "Java",
        "message": "Build path specifies execution environment JavaSE-1.6. There are no JREs installed in the workspace that are strictly compatible with this environment. "
      }
    ]
  }
}, module: kak_lsp::language_server_transport:151
```

</details>

**Comment by basbebe** [comment]
> I just downloaded a release and unpacked it to a user dir
> 
> 
> 
> I do get the error flags on the jenkins demo project:


What about a single Java File in a Directory that is not within a project?

I don't get flags in those…

**Comment by krobelus** [comment]
That also works for me. I copied App.java from the demo project to an empty directory. It failed intermittently (I think because the language server was still running) but now it works consistently.

```
App.java:1:1: warning:App.java is a non-project file, only syntax errors are reported
App.java:3:1: error:Syntax error on token "asdf", delete this token
```

Make sure to update to latest `kak-lsp` master for the workaround I added.

**Comment by krobelus** [comment]
Code actions don't work because, as the error message says, they don't support `workspace/executeCommand` (despite advertising it).
There is an open issue at https://github.com/eclipse/eclipse.jdt.ls/issues/376

They send this

```json
Nov 12 19:50:54.285 DEBG From server: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "title": "Organize imports",
      "kind": "source.organizeImports",
      "diagnostics": [],
      "command": {
        "title": "Organize imports",
        "command": "java.apply.workspaceEdit",
        "arguments": [
          {
            "changes": {
              "file:///tmp/App.java": [
                {
                  "range": {
                    "start": {
                      "line": 0,
                      "character": 26
                    },
                    "end": {
                      "line": 7,
                      "character": 0
                    }
                  },
                  "newText": "\n\n"
                }
              ]
            }
          }
        ]
      }
    },
  ]
}, module: kak_lsp::language_server_transport:151
```

so we send

```json
Nov 12 19:50:59.482 DEBG To server: {
  "jsonrpc": "2.0",
  "method": "workspace/executeCommand",
  "params": {
    "arguments": [
      {
        "changes": {
          "file:///tmp/App.java": [
            {
              "newText": "\n\n",
              "range": {
                "end": {
                  "character": 0,
                  "line": 7
                },
                "start": {
                  "character": 26,
                  "line": 0
                }
              }
            }
          ]
        }
      }
    ],
    "command": "java.apply.workspaceEdit"
  },
  "id": 2
}, module: kak_lsp::language_server_transport:177
```

There is a possible fix if you are willing to patch your language server: https://github.com/eclipse/eclipse.jdt.ls/issues/376#issuecomment-622924117

It looks like the VSCode plugin uses `codeAction/resolve`. I guess I can try that sometime

**Comment by dzamo** [comment]
Thanks for investigating @krobelus.  I'll patch jdt.ls for now and maybe keep an eye out for a different Java lang server since jdt.ls seems to be more invested in not breaking VSCode than in protocol compliance.

**Comment by krobelus** [comment]
Sounds nice, let me know if that doesn't work. I'm sure there is a sensible fix/workaround we can do, we just need  to find it. Fixing this is more important to me than new features, plus I feel sorry for you having to use Java :crying_cat_face:

**Comment by dzamo** [comment]
Lol.  Unfortunately that patch shared on the jdt.ls issue comment is not enough to do the trick and we stay at

```
kak-lsp: java language server error: 'Java language server doesn''t support the command ''java.apply.workspaceEdit''.'
```

for now.

**Comment by basbebe** [comment]
@dzamo before I used jdt.ls I used this one:
 https://github.com/georgewfraser/java-language-server

It gave me less problems to compile and it was easier to set up but I think I had also some problems and missing features.
Can't remember what it was though, I'm not using Java too often at the moment.

**Comment by basbebe** [comment]
> @dzamo before I used jdt.ls I used this one:
>  https://github.com/georgewfraser/java-language-server
> 
> It gave me less problems to compile and it was easier to set up but I think I had also some problems and missing features.
> Can't remember what it was though, I'm not using Java too often at the moment.

I remember now that it doesn't support formatting which I would have liked.

**Comment by krobelus** [comment]
Formatting is fairly easy to set up independently. I have this in my config:

```kak
hook -group my global WinSetOption filetype=(c|cpp|java) %{
	set-option buffer formatcmd "clang-format -style=file -assume-filename=%val{buffile}"
}
```

**Comment by krobelus** [comment]
looks like there is some progress in `jdtls`, there is a PR that makes it use the generic `workspace.applyEdit` for some code actions, see https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2962

**Comment by jnturton** [comment]
Thanks for your work there to drive the enhancement to a good place!
