### ISSUE TITLE
completions seems to crash rust-analyzer

### ISSUE THREAD

**Issue by uncomfyhalomacro** [kak-lsp/kak-lsp#701]
```
session  = "32629"
buffile  = "/home/uncomfy/development/projects/otap/otap/src/main.rs"
filetype = "rust"
version  = 51
method   = "textDocument/didChange"
hook     = true
[params]
draft    = """
use std::
fn main() {
    println!(\"Hello, world!\");
}
"""
, module: kak_lsp::editor_transport:138
Nov 25 15:18:50.024 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:60
Nov 25 15:18:50.024 INFO Found project root "/home/uncomfy/development/projects/otap/otap" because it contains "Cargo.toml", module: kak_lsp::project_root:43
Nov 25 15:18:50.024 DEBG Routing editor request to Route { session: "32629", server_name: "rust-analyzer", root: "/home/uncomfy/development/projects/otap/otap" }, module: kak_lsp::session:120
Nov 25 15:18:50.024 DEBG Language servers rust-analyzer are still not initialized, parking request, module: kak_lsp::controller:184
Nov 25 15:18:50.151 DEBG From server rust-analyzer: {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"positionEncoding":"utf-8","textDocumentSync":{"openClose":true,"change":2,"save":{}},"selectionRangeProvider":true,"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[":",".","'","("],"completionItem":{"labelDetailsSupport":false}},"signatureHelpProvider":{"triggerCharacters":["(",",","<"]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite"],"resolveProvider":true},"codeLensProvider":{"resolveProvider":true},"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"=","moreTriggerCharacter":[".",">","{","("]},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"declarationProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true},"fileOperations":{"willRename":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.rs","matches":"file"}},{"scheme":"file","pattern":{"glob":"**","matches":"folder"}}]}}},"callHierarchyProvider":true,"semanticTokensProvider":{"legend":{"tokenTypes":["comment","decorator","enumMember","enum","function","interface","keyword","macro","method","namespace","number","operator","parameter","property","string","struct","typeParameter","variable","angle","arithmetic","attribute","attributeBracket","bitwise","boolean","brace","bracket","builtinAttribute","builtinType","character","colon","comma","comparison","constParameter","derive","deriveHelper","dot","escapeSequence","invalidEscapeSequence","formatSpecifier","generic","label","lifetime","logical","macroBang","parenthesis","punctuation","selfKeyword","selfTypeKeyword","semicolon","typeAlias","toolModule","union","unresolvedReference"],"tokenModifiers":["documentation","declaration","static","defaultLibrary","async","attribute","callable","constant","consuming","controlFlow","crateRoot","injected","intraDocLink","library","macro","mutable","public","reference","trait","unsafe"]},"range":true,"full":{"delta":true}},"inlayHintProvider":{"resolveProvider":true},"experimental":{"externalDocs":true,"hoverRange":true,"joinLines":true,"matchingBrace":true,"moveItem":true,"onEnter":true,"openCargoToml":true,"parentModule":true,"runnables":{"kinds":["cargo"]},"ssr":true,"workspaceSymbolScopeKindFiltering":true}},"serverInfo":{"name":"rust-analyzer","version":"1.74.0 (79e9716 2023-11-13)"}}}, module: kak_lsp::language_server_transport:168
Nov 25 15:18:50.151 DEBG To server rust-analyzer: {"jsonrpc":"2.0","method":"initialized","params":{}}, module: kak_lsp::language_server_transport:198
Nov 25 15:18:50.151 DEBG To server rust-analyzer: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"rust","text":"\nfn main() {\n    println!(\"Hello, world!\");\n}\n","uri":"file:///home/uncomfy/development/projects/otap/otap/src/main.rs","version":51}}}, module: kak_lsp::language_server_transport:198
Nov 25 15:18:50.151 ERRO panic: panicked at src/language_features/completion.rs:20:68:
called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, at: None, message: "missing field `have_kakoune_feature_filtertext`", key: [] } }, module: kak_lsp:364
Nov 25 15:18:50.151 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:19
Nov 25 15:18:50.151 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:209
Nov 25 15:18:50.151 DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:102
Nov 25 15:18:50.486 DEBG Language server closed pipe, stopping reading, module: kak_lsp::language_server_transport:146
Nov 25 15:18:50.486 ERRO Language server error: Error: client exited without proper shutdown sequence
, module: kak_lsp::language_server_transport:68
Nov 25 15:18:51.151 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:21
Nov 25 15:18:51.151 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:19
Nov 25 15:18:51.151 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:21
Nov 25 15:18:51.151 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:19
Nov 25 15:18:51.151 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:21
```

Idk why it gets restarted but that is how i got the logs though. It seems to crash and attempts to restart the lsp.

See video for context 

https://github.com/kak-lsp/kak-lsp/assets/66054069/a528df1a-c5c3-43eb-a788-8675f43c43af

**Comment by krobelus** [comment]
On Sat, Nov 25, 2023 at 07:25:59AM -0800, Soc Virnyl S. Estela wrote:
> Nov 25 15:18:50.151 ERRO panic: panicked at src/language_features/completion.rs:20:68:
> called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, at: None, message: "missing field `have_kakoune_feature_filtertext`", key: [] } }, module: kak_lsp:364

The "have_kakoune_feature_filtertext" field was removed in master recently.
This error means you pulled latest kak-lsp but are not running the latest binary.
Make sure to reinstall after pulling. Use a command like `cargo install --path . --locked --force`

I guess this one we could handle more gracefully but in general it's too much effort to provide forward compat

**Comment by uncomfyhalomacro** [comment]
Oh that makes sense! Sorry for the bother!
